name: Build Archi Plugin
description: This actions builds an Archi plugin

inputs:
  plugin:
    description: "Plugin name (e.g. com.archimatetool.script)"
    required: true

runs:
  using: composite
  steps:
    - name: Install xmlstarlet
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet

    - name: Add plugin modules and generate pom.xml
      shell: bash
      run: |
        set -e

        NAMESPACE="http://maven.apache.org/POM/4.0.0"
        PLUGIN="${{ inputs.plugin }}"
        EXCLUDE="${PLUGIN}.tests"

        for dir in ${PLUGIN}*; do
          [ -d "$dir" ] || continue

          module="$(basename "$dir")"
          [ "$module" = "$EXCLUDE" ] && continue

          cp pom-template.xml "$dir/pom.xml"

          if [[ "$module" == *feature ]]; then
            version="$(xmlstarlet sel \
              -t -v "/feature/@version" \
              "$dir/feature.xml")"
          else
            version="$(grep '^Bundle-Version:' \
              "$dir/META-INF/MANIFEST.MF" | cut -d' ' -f2)"
          fi

          version="${version%.qualifier}-SNAPSHOT"

          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project" -t elem -n "artifactId" -v "$module" \
            -s "/x:project" -t elem -n "version" -v "$version" \
            "$dir/pom.xml" \

          cat $dir/pom.xml \

          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project/x:modules" -t elem -n "module" -v "$module" \
            pom.xml
        done
