name: Build Archi Plugin
description: Builds an Archi plugin

inputs:
  name:
    description: "Plugin name (e.g. com.archimatetool.script)"
    required: true
  source:
    description: "Repository of the plugin"
    required: true

runs:
  using: composite
  steps:
    - name: Install xmlstarlet
      shell: bash
      run: sudo apt-get -qq update && sudo apt-get -qq install -y xmlstarlet

    - name: Retrieve the source
      shell: bash
      run: curl -s -L https://github.com/${{ inputs.source }}/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

    - name: Generate the build descriptors
      shell: bash
      run: |
        set -e

        NAMESPACE="http://maven.apache.org/POM/4.0.0"
        PLUGIN="${{ inputs.name }}"
        POM="pom.xml"
        EXCLUDE=("${PLUGIN}.tests" "${PLUGIN}.feature")

        for dir in ${PLUGIN}*; do
          [ -d "$dir" ] || continue

          module="$(basename "$dir")"

          if [[ " ${EXCLUDE[*]} " == *" $module "* ]]; then
            continue
          fi

          # Copy pom-template.xml
          cp pom-template.xml "$dir/pom.xml"

          # Extract version from MANIFEST.MF
          manifest="$dir/META-INF/MANIFEST.MF"
          version="$(grep '^Bundle-Version:' "$manifest" | cut -d' ' -f2)"
          version="${version%.qualifier}-SNAPSHOT"

          # Set artifactId and version in module pom.xml
          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project" -t elem -n "artifactId" -v "$module" \
            -s "/x:project" -t elem -n "version" -v "$version" \
            "$dir/pom.xml"

          # Add module to root pom.xml
          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project/x:modules" \
            -t elem -n "module" -v "$module" \
            "$POM"
        done

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven
