name: Build Archi Plugin
description: Builds an Archi plugin

inputs:
  name:
    description: "Plugin name (e.g. com.archimatetool.script)"
    required: true
  source:
    description: "Repository of the plugin"
    required: true

runs:
  using: composite
  steps:
    - name: Install xmlstarlet
      shell: bash
      run: sudo apt-get -qq update && sudo apt-get -qq install -y xmlstarlet

    - name: Retrieve the source
      shell: bash
      run: curl -s -L https://github.com/${{ inputs.source }}/archive/refs/heads/master.tar.gz | tar xz --strip-components=1

    - name: Generate the build descriptors
      shell: bash
      run: |
        set -e
        NAMESPACE="http://maven.apache.org/POM/4.0.0"
        PLUGIN="${{ inputs.name }}"
        POM="pom.xml"
        EXCLUDE=("${PLUGIN}.tests" "${PLUGIN}.feature")

        for dir in ${PLUGIN}*; do
          [ -d "$dir" ] || continue

          module="$(basename "$dir")"

          if [[ " ${EXCLUDE[*]} " == *" $module "* ]]; then
            continue
          fi

          cp pom-template.xml "$dir/pom.xml"
          manifest="$dir/META-INF/MANIFEST.MF"
          version="$(grep '^Bundle-Version:' "$manifest" | cut -d' ' -f2)"
          version="${version%.qualifier}-SNAPSHOT"

          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project" -t elem -n "artifactId" -v "$module" \
            -s "/x:project" -t elem -n "version" -v "$version" \
            "$dir/pom.xml"

          xmlstarlet ed -L \
            -N x="$NAMESPACE" \
            -s "/x:project/x:modules" \
            -t elem -n "module" -v "$module" \
            "$POM"
        done

    - name: Detect Java version
      shell: bash
      run: |
        set -e
        echo "JAVA_VERSION=$(grep '^Bundle-RequiredExecutionEnvironment:' "${{ inputs.name }}/META-INF/MANIFEST.MF" \
          | sed -E 's/.*JavaSE-([0-9]+).*/\1/')" >> "$GITHUB_ENV"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: maven

    - name: Build
      shell: bash
      run: mvn -B -q clean -DskipTests verify
  
    - name: Prepare JARs for artifact
      shell: bash
      run: |
        mkdir tmp
        cp ${{ inputs.name }}*/target/*.jar tmp/
        touch tmp/archi-plugin

    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.archiplugin
        path: tmp/*
